// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ContosoApi.Models
{
    public class DepartmentInsertResult
    {
        public int DepartmentId { get; set; }
        public byte[] RowVersion { get; set; }
    }
}