// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoApi.Models
{
    [Table("Person")]
    public partial class Person
    {
        public Person()
        {
            CourseInstructors = new HashSet<CourseInstructor>();
            Departments = new HashSet<Department>();
            Enrollments = new HashSet<Enrollment>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? HireDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EnrollmentDate { get; set; }
        [Required]
        [StringLength(128)]
        public string Discriminator { get; set; }
        public DateTime DateModified { get; set; }
        public bool IsDeleted { get; set; }

        [InverseProperty("Instructor")]
        public virtual OfficeAssignment OfficeAssignment { get; set; }
        [InverseProperty(nameof(CourseInstructor.Instructor))]
        public virtual ICollection<CourseInstructor> CourseInstructors { get; set; }
        [InverseProperty(nameof(Department.Instructor))]
        public virtual ICollection<Department> Departments { get; set; }
        [InverseProperty(nameof(Enrollment.Student))]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}